# Generated by Django 5.2.5 on 2025-08-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_review_text_review_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_text',
        ),
    ]
