# Generated by Django 5.2.5 on 2025-08-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_review_review_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='review',
        ),
    ]
