# Generated by Django 5.2.5 on 2025-08-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_review_text_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
