# Generated by Django 5.2.5 on 2025-08-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=10),
        ),
    ]
