# Generated by Django 5.2.5 on 2025-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_created_at_alter_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
