# Generated by Django 5.2.5 on 2025-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=10),
        ),
    ]
